### ISSUE TITLE
The detection algorithm

### ISSUE THREAD

**Issue by mosfe** [prophesee-ai/prophesee-automotive-dataset-toolbox#24]
Hello，I am interseted in your paper, this is so interseting.
But I do not find the RED algorithm you proposed in the repo, the codes in the src are only related to the dataset.
If I want to verify the performance, what should I do? Could you give me some suggestions.
Hope for your reply.

**Comment by leonelppsee** [comment]
Hello @mosfe,
The RED algorithm is not available in the repo indeed.
However, since release [Metavision Intelligence 3.x](https://www.prophesee.ai/metavision-intelligence-sdk-download/), Python source code is now distributed free with our installers / deb packages, so you just have to download / install Metavision and check the files deployed to his Python system site packages folder.For example:
- on Ubuntu 18 :  /usr/lib/python3/dist-packages/metavision_ml/detection
- on Windows 10 : C:\Program Files\Prophesee\lib\python3\site-packages\metavision_ml
