### ISSUE TITLE
Is it possible to obtain object tracking annotations on Gen1/1Mpx?

### ISSUE THREAD

**Issue by Wuziyi616** [prophesee-ai/prophesee-automotive-dataset-toolbox#30]
Hi, I wonder if it's possible to get object tracking annotations on Gen1 or 1Mpx dataset? I read the NeurIPS paper of 1Mpx dataset, in Section 5.1 page 7, the paper says "we compute the Intersection over Union (IoU) between 1000 **ground truth tracks** from the validation set and the predicted boxes". However, according to both papers, only `t, (x, y, h, w), class_id` are provided as annotations. So I wonder how are you able to extract GT tracks of objects?

I inspect the annotation `npy` files of Gen1 test set, there is indeed a field called `track_id`. However, I don't think that's useful as it seems to be unique for each object bbox (see below). I haven't downloaded 1Mpx as it's much larger, so not sure if it's provided there. Thanks in advance!

![img](https://github.com/prophesee-ai/prophesee-automotive-dataset-toolbox/assets/37072215/f771ba7a-df32-428c-a859-780d9d3c05a2)

**Comment by Wuziyi616** [comment]
One possible way I can think of is to associate bboxes pairs that are 1) from the same category and 2) have short offsets (especially the x coordinate). Is that what you used in the paper (if the tracking id is not provided)

**Comment by Wuziyi616** [comment]
Would be great if you can kindly take a look @lbristiel-psee. Thanks!

**Comment by lbristiel-psee** [comment]
Hi @Wuziyi616 

sorry for the delay to come back to you.

So indeed, for the Gen1 dataset, we don't have track_id (we have a constant value in the label file as you saw, just because it is not relevant data). Your suggestion to " associate bboxes pairs" will most probably not work as the delta_t between 2 annotations is quite large so objects can have moved a lot.

On the other hand, inthe 1Mpx dataset, trackings ids are provided in the label file (so value won't be constant). But note that theses ids these ids come from automated labeling protocol, 
so we do not guarantee the quality.

Hope this helps,
Laurent

**Comment by Wuziyi616** [comment]
Thanks for your reply!
